name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_PORT: ${{ secrets.EC2_PORT }}
      EC2_USER: ${{ secrets.EC2_USER }}
      DEPLOY_DIR: '/home/ubuntu/Shell_Script-Mini-Project'
      DEPLOY_SCRIPT: 'deploy.sh'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy latest code
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ env.EC2_PORT }} ${{ env.EC2_USER }}@${{ env.EC2_HOST }} << EOF
          cd ${DEPLOY_DIR}
          git pull origin main
          ls -l ${DEPLOY_SCRIPT}  # Ensure the script exists
          bash ${DEPLOY_SCRIPT}
        EOF

    - name: Notify success
      if: success()
      run: echo "Deployment successful!"

    - name: Notify failure
      if: failure()
      run: echo "Deployment failed."

